### PR TITLE
docker containerized

### PR DESCRIPTION
**Pull request by Chethan34**
please check with its working now, let me know if you have any more issues with docker.

modifications are seen in commits.

checks:
1. docker-compose build
2. docker-compose up
3. docker-compose down

### CODE REVIEW

**Comment by TaylorC19** [comment]
Thank you for working on this. I was testing your fork, and I am getting an error in the logs. 
This screenshot is from your fork. I cloned your fork and created the `.env` and `.env.docker` files (though I don't think they should be necessary as the docker-compose file now refers to the docker example file). It seems to be an issue in the node modules. I ran `npm install` again and rebuilt the container, but the error persisted.
image

**Comment by Chethan34** [comment]
Thanks for the update.

check again i have made changes to dependencies which is based on hit and trial.

**Comment by TaylorC19** [comment]
I was able to run the docker container, but none of the endpoints are accessible. This screenshot also shows that swagger isn't able to find the endpoints

**Comment by TaylorC19** [comment]
image

**Comment by TaylorC19** [comment]
Example of how it normally looks on main.
image

**Comment by Chethan34** [comment]
there is one or the other dependency conflicts. Need sometime to go through overall code and the built idea. I got no knowledge of nestjs to be honest or postgres/sql in fact.

**Pull request closed without merging**
